language: objective-c
osx_image: xcode9.2

before_install:
  - pod install

script:
  - xcodebuild -workspace NetDiag.xcworkspace -scheme NetDiagTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5s,OS=11.2' test
